PARENTS = 1
ELEVATION_UNCERT = 0
MIN_RESIDUAL = 2
MAX_RESIDUAL = 10
MIN_TOTAL_VOLUME = 200000000.0
MAX_TOTAL_VOLUME = 200000000.0
MIN_PULSE_VOLUME = 200000.0
MAX_PULSE_VOLUME = 200000.0
RUNS = 1
ASCII_FLOW_MAP = 1
DEM_FILE = ../DEMs_Lava_Benchmark/MaunaLoa.asc
EVENTS_FILE = events.in