PARENTS = 1
ELEVATION_UNCERT = 0
MIN_RESIDUAL = 3.5e-06
MAX_RESIDUAL = 0.02
MIN_TOTAL_VOLUME = 0.00111
MAX_TOTAL_VOLUME = 0.00111
MIN_PULSE_VOLUME = 5e-06
MAX_PULSE_VOLUME = 5e-06
RUNS = 1
ASCII_FLOW_MAP = 1
DEM_FILE = ../topography_incline_triangle.asc
EVENTS_FILE = events.in