PARENTS = 1
ELEVATION_UNCERT = 0
MIN_RESIDUAL = 4e-05
MAX_RESIDUAL = 0.001
MIN_TOTAL_VOLUME = 3.432e-06
MAX_TOTAL_VOLUME = 3.432e-06
MIN_PULSE_VOLUME = 3.4319999999999997e-09
MAX_PULSE_VOLUME = 3.432e-08
RUNS = 1
ASCII_FLOW_MAP = 1
DEM_FILE = ../DEMs_Lava_Benchmark/Benchmark_Axisymmetric.asc
EVENTS_FILE = events.in